apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qvy6pi1wg-dotnet-basic
  janus-idp.io/tekton: qvy6pi1wg-dotnet-basic
  backstage.io/kubernetes-id: qvy6pi1wg-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qvy6pi1wg-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
